from .schemas import DatabaseStatus, DatabaseProvider

SEED_DATABASES = [
    {
        "id": "aws-rds-1",
        "provider": DatabaseProvider.aws,
        "service": "Amazon RDS",
        "engine": "postgres",
        "region": "us-east-1",
        "endpoint": "rds-prod-1.abcxyz.amazonaws.com",
        "storage_gb": 200,
        "status": DatabaseStatus.available,
        "subscription": "payments",
        "tags": ["prod", "critical"],
        "version": "15.4",
        "azure_tenant": None,
    },
    {
        "id": "aws-aurora-2",
        "provider": DatabaseProvider.aws,
        "service": "Aurora Serverless",
        "engine": "mysql",
        "region": "us-west-2",
        "endpoint": "aurora-mysql.cluster-xyz.us-west-2.rds.amazonaws.com",
        "storage_gb": 120,
        "status": DatabaseStatus.maintenance,
        "subscription": "growth",
        "tags": ["staging"],
        "version": "8.0.mysql_aurora.3.04.0",
        "azure_tenant": None,
    },
    {
        "id": "azure-sql-1",
        "provider": DatabaseProvider.azure,
        "service": "Azure SQL",
        "engine": "mssql",
        "region": "eastus",
        "endpoint": "sql-prod-eastus.database.windows.net",
        "storage_gb": 512,
        "status": DatabaseStatus.available,
        "subscription": "analytics",
        "tags": ["prod"],
        "version": "SQL Server 2022",
        "azure_tenant": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    },
    {
        "id": "cosmos-mongo-1",
        "provider": DatabaseProvider.azure,
        "service": "Cosmos DB",
        "engine": "mongodb",
        "region": "westeurope",
        "endpoint": "cosmos-mongo-1.mongo.cosmos.azure.com",
        "storage_gb": 80,
        "status": DatabaseStatus.warning,
        "subscription": "ml-platform",
        "tags": ["beta", "eventing"],
        "version": "4.2",
        "azure_tenant": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    },
]


