from .schemas import DatabaseStatus, DatabaseProvider

SEED_DATABASES = [
    {
        "id": "aws-rds-1",
        "provider": DatabaseProvider.aws,
        "service": "Amazon RDS",
        "engine": "postgres",
        "region": "us-east-1",
        "endpoint": "rds-prod-1.abcxyz.amazonaws.com",
        "storage_gb": 200,
        "status": DatabaseStatus.available,
        "subscription": "511610426163",  # ITH-IO account
        "tags": ["prod", "critical"],
        "version": "15.4",
        "azure_tenant": None,
    },
    {
        "id": "aws-aurora-2",
        "provider": DatabaseProvider.aws,
        "service": "Aurora Serverless",
        "engine": "mysql",
        "region": "us-west-2",
        "endpoint": "aurora-mysql.cluster-xyz.us-west-2.rds.amazonaws.com",
        "storage_gb": 120,
        "status": DatabaseStatus.maintenance,
        "subscription": "811731516858",  # buildosith account
        "tags": ["staging"],
        "version": "8.0.mysql_aurora.3.04.0",
        "azure_tenant": None,
    },
    {
        "id": "azure-sql-1",
        "provider": DatabaseProvider.azure,
        "service": "Azure SQL",
        "engine": "mssql",
        "region": "eastus",
        "endpoint": "sql-prod-eastus.database.windows.net",
        "storage_gb": 512,
        "status": DatabaseStatus.available,
        "subscription": "analytics",
        "tags": ["prod"],
        "version": "SQL Server 2022",
        "azure_tenant": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    },
    {
        "id": "cosmos-mongo-1",
        "provider": DatabaseProvider.azure,
        "service": "Cosmos DB",
        "engine": "mongodb",
        "region": "westeurope",
        "endpoint": "cosmos-mongo-1.mongo.cosmos.azure.com",
        "storage_gb": 80,
        "status": DatabaseStatus.warning,
        "subscription": "ml-platform",
        "tags": ["beta", "eventing"],
        "version": "4.2",
        "azure_tenant": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    },
]


SEED_BUILD_CATALOG = [
    # SQL Server
    {
        "engine": "SQL Server",
        "version": "SQL Server 2022",
        "build_number": "16.0.4095.4",
        "release_date": "2024-09-12",
        "update": "CU14",
        "doc_label": "KB5038325",
        "doc_url": "https://support.microsoft.com/en-us/help/5038325",
        "support_end": "2028-01-11",
        "maintenance_end": "2033-01-11",
    },
    {
        "engine": "SQL Server",
        "version": "SQL Server 2022",
        "build_number": "16.0.4085.2",
        "release_date": "2024-08-14",
        "update": "CU13",
        "doc_label": "KB5036432",
        "doc_url": "https://support.microsoft.com/en-us/help/5036432",
        "support_end": "2028-01-11",
        "maintenance_end": "2033-01-11",
    },
    {
        "engine": "SQL Server",
        "version": "SQL Server 2019",
        "build_number": "15.0.4375.4",
        "release_date": "2024-09-12",
        "update": "CU28",
        "doc_label": "KB5038325",
        "doc_url": "https://support.microsoft.com/en-us/help/5038325",
        "support_end": "2025-02-28",
        "maintenance_end": "2030-01-08",
    },
    {
        "engine": "SQL Server",
        "version": "SQL Server 2017",
        "build_number": "14.0.3465.1",
        "release_date": "2024-01-11",
        "update": "CU31 GDR",
        "doc_label": "KB5029376",
        "doc_url": "https://support.microsoft.com/en-us/help/5029376",
        "support_end": "2022-10-11",
        "maintenance_end": "2027-10-12",
    },
    {
        "engine": "SQL Server",
        "version": "SQL Server 2016",
        "build_number": "13.0.7037.1",
        "release_date": "2024-01-09",
        "update": "CU17 GDR",
        "doc_label": "KB5029186",
        "doc_url": "https://support.microsoft.com/en-us/help/5029186",
        "support_end": "2021-07-13",
        "maintenance_end": "2026-07-14",
    },
    {
        "engine": "SQL Server",
        "version": "SQL Server 2014",
        "build_number": "12.0.6449.1",
        "release_date": "2024-02-13",
        "update": "CU4 GDR",
        "doc_label": "KB5032968",
        "doc_url": "https://support.microsoft.com/en-us/help/5032968",
        "support_end": "2019-07-09",
        "maintenance_end": "2024-07-09",
    },

    # PostgreSQL (sourced from endoflife.date)
    {
        "engine": "PostgreSQL",
        "version": "PostgreSQL 18",
        "build_number": "18.1",
        "release_date": "2025-11-10",
        "update": "18.1",
        "doc_label": "Release 18.1",
        "doc_url": "https://www.postgresql.org/docs/release/18.1/",
        "support_end": "2030-11-14",
    },
    {
        "engine": "PostgreSQL",
        "version": "PostgreSQL 17",
        "build_number": "17.7",
        "release_date": "2025-11-10",
        "update": "17.7",
        "doc_label": "Release 17.7",
        "doc_url": "https://www.postgresql.org/docs/release/17.7/",
        "support_end": "2029-11-08",
    },
    {
        "engine": "PostgreSQL",
        "version": "PostgreSQL 16",
        "build_number": "16.11",
        "release_date": "2025-11-10",
        "update": "16.11",
        "doc_label": "Release 16.11",
        "doc_url": "https://www.postgresql.org/docs/release/16.11/",
        "support_end": "2028-11-09",
    },
    {
        "engine": "PostgreSQL",
        "version": "PostgreSQL 15",
        "build_number": "15.15",
        "release_date": "2025-11-10",
        "update": "15.15",
        "doc_label": "Release 15.15",
        "doc_url": "https://www.postgresql.org/docs/release/15.15/",
        "support_end": "2027-11-11",
    },
    {
        "engine": "PostgreSQL",
        "version": "PostgreSQL 14",
        "build_number": "14.20",
        "release_date": "2025-11-10",
        "update": "14.20",
        "doc_label": "Release 14.20",
        "doc_url": "https://www.postgresql.org/docs/release/14.20/",
        "support_end": "2026-11-12",
    },

    # MySQL
    {
        "engine": "MySQL",
        "version": "MySQL 8.4 LTS",
        "build_number": "8.4",
        "release_date": "2024-04-30",
        "update": "8.4 (LTS)",
        "doc_label": "MySQL 8.4 LTS",
        "doc_url": "https://docs.oracle.com/en-us/iaas/mysql-database/doc/mysql-server-versions.html#MYAAS-GUID-BA832E37-B752-42AA-890A-2ACAD44B2F6C",
        "support_end": "2032-04-30",
    },
    {
        "engine": "MySQL",
        "version": "MySQL 8.0",
        "build_number": "8.0",
        "release_date": "2018-04-19",
        "update": "8.0 (GA)",
        "doc_label": "MySQL 8.0 GA",
        "doc_url": "https://docs.oracle.com/en-us/iaas/mysql-database/doc/mysql-server-versions.html#MYAAS-GUID-BA832E37-B752-42AA-890A-2ACAD44B2F6C",
        "support_end": "2026-04-30",
    },
    {
        "engine": "MySQL",
        "version": "MySQL 5.7",
        "build_number": "5.7",
        "release_date": "2015-10-21",
        "update": "5.7 (GA)",
        "doc_label": "MySQL 5.7 GA",
        "doc_url": "https://docs.oracle.com/en-us/iaas/mysql-database/doc/mysql-server-versions.html#MYAAS-GUID-BA832E37-B752-42AA-890A-2ACAD44B2F6C",
        "support_end": "2023-10-31",
    },
]


